package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_healthedit{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("panelbuildinglist").vw.setWidth((int)((100d / 100 * width)));
views.get("label1").vw.setHeight((int)((8d / 100 * height)));
views.get("label1").vw.setTop((int)((2d / 100 * height)));
views.get("label1").vw.setLeft((int)((5d / 100 * width)));
views.get("label1").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("healthlabel").vw.setHeight((int)((5d / 100 * height)));
views.get("healthlabel").vw.setTop((int)((views.get("label1").vw.getTop())+(views.get("label1").vw.getHeight())+(2d / 100 * height)));
views.get("healthlabel").vw.setLeft((int)((5d / 100 * width)));
views.get("healthlabel").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel1").vw.setHeight((int)((7d / 100 * height)));
views.get("panel1").vw.setLeft((int)((5d / 100 * width)));
views.get("panel1").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel1").vw.setTop((int)((views.get("healthlabel").vw.getTop())+(views.get("healthlabel").vw.getHeight())));
views.get("healthname").vw.setHeight((int)((views.get("panel1").vw.getHeight())));
views.get("healthname").vw.setLeft((int)((0d / 100 * width)));
views.get("healthname").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("healthname").vw.setTop((int)((0d / 100 * height)));
views.get("lbltypeofhealth").vw.setHeight((int)((views.get("healthlabel").vw.getHeight())));
views.get("lbltypeofhealth").vw.setLeft((int)((5d / 100 * width)));
views.get("lbltypeofhealth").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lbltypeofhealth").vw.setTop((int)((views.get("panel1").vw.getTop())+(views.get("panel1").vw.getHeight())+(2d / 100 * height)));
views.get("paneltypehealth").vw.setHeight((int)((views.get("panel1").vw.getHeight())));
views.get("paneltypehealth").vw.setTop((int)((views.get("lbltypeofhealth").vw.getTop())+(views.get("lbltypeofhealth").vw.getHeight())));
views.get("paneltypehealth").vw.setLeft((int)((5d / 100 * width)));
views.get("paneltypehealth").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("typeofhealth").vw.setHeight((int)((views.get("paneltypehealth").vw.getHeight())));
views.get("typeofhealth").vw.setTop((int)((views.get("healthname").vw.getTop())));
views.get("typeofhealth").vw.setLeft((int)((0d / 100 * width)));
views.get("typeofhealth").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblheadoffice").vw.setHeight((int)((views.get("lbltypeofhealth").vw.getHeight())));
views.get("lblheadoffice").vw.setLeft((int)((5d / 100 * width)));
views.get("lblheadoffice").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lblheadoffice").vw.setTop((int)((views.get("paneltypehealth").vw.getTop())+(views.get("paneltypehealth").vw.getHeight())+(2d / 100 * height)));
views.get("pnlhead").vw.setHeight((int)((views.get("paneltypehealth").vw.getHeight())));
views.get("pnlhead").vw.setTop((int)((views.get("lblheadoffice").vw.getTop())+(views.get("lblheadoffice").vw.getHeight())));
views.get("pnlhead").vw.setLeft((int)((5d / 100 * width)));
views.get("pnlhead").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("headoffice").vw.setHeight((int)((views.get("pnlhead").vw.getHeight())));
views.get("headoffice").vw.setTop((int)((views.get("typeofhealth").vw.getTop())));
views.get("headoffice").vw.setLeft((int)((0d / 100 * width)));
views.get("headoffice").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblmedical").vw.setHeight((int)((views.get("lblheadoffice").vw.getHeight())));
views.get("lblmedical").vw.setLeft((int)((5d / 100 * width)));
views.get("lblmedical").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lblmedical").vw.setTop((int)((views.get("pnlhead").vw.getTop())+(views.get("pnlhead").vw.getHeight())+(2d / 100 * height)));
views.get("pnltcs").vw.setHeight((int)((views.get("pnlhead").vw.getHeight())));
views.get("pnltcs").vw.setTop((int)((views.get("lblmedical").vw.getTop())+(views.get("lblmedical").vw.getHeight())));
views.get("pnltcs").vw.setLeft((int)((5d / 100 * width)));
views.get("pnltcs").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("nummedical").vw.setHeight((int)((views.get("headoffice").vw.getHeight())));
views.get("nummedical").vw.setTop((int)((views.get("headoffice").vw.getTop())));
views.get("nummedical").vw.setLeft((int)((0d / 100 * width)));
views.get("nummedical").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblnonmedical").vw.setHeight((int)((views.get("lblmedical").vw.getHeight())));
views.get("lblnonmedical").vw.setLeft((int)((5d / 100 * width)));
views.get("lblnonmedical").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lblnonmedical").vw.setTop((int)((views.get("pnltcs").vw.getTop())+(views.get("pnltcs").vw.getHeight())+(2d / 100 * height)));
views.get("panel4").vw.setHeight((int)((views.get("pnltcs").vw.getHeight())));
views.get("panel4").vw.setTop((int)((views.get("lblnonmedical").vw.getTop())+(views.get("lblnonmedical").vw.getHeight())));
views.get("panel4").vw.setLeft((int)((5d / 100 * width)));
views.get("panel4").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("numnonmedical").vw.setHeight((int)((views.get("nummedical").vw.getHeight())));
views.get("numnonmedical").vw.setTop((int)((views.get("nummedical").vw.getTop())));
views.get("numnonmedical").vw.setLeft((int)((0d / 100 * width)));
views.get("numnonmedical").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblstandingyear").vw.setHeight((int)((views.get("lblnonmedical").vw.getHeight())));
views.get("lblstandingyear").vw.setLeft((int)((5d / 100 * width)));
views.get("lblstandingyear").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lblstandingyear").vw.setTop((int)((views.get("panel4").vw.getTop())+(views.get("panel4").vw.getHeight())+(2d / 100 * height)));
views.get("panel2").vw.setHeight((int)((views.get("panel4").vw.getHeight())));
views.get("panel2").vw.setTop((int)((views.get("lblstandingyear").vw.getTop())+(views.get("lblstandingyear").vw.getHeight())));
views.get("panel2").vw.setLeft((int)((5d / 100 * width)));
views.get("panel2").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("standingyear").vw.setHeight((int)((views.get("numnonmedical").vw.getHeight())));
views.get("standingyear").vw.setTop((int)((views.get("numnonmedical").vw.getTop())));
views.get("standingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("standingyear").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblbuildingarea").vw.setTop((int)((views.get("panel2").vw.getTop())+(views.get("panel2").vw.getHeight())+(2d / 100 * height)));
views.get("lblbuildingarea").vw.setHeight((int)((views.get("lblstandingyear").vw.getHeight())));
views.get("lblbuildingarea").vw.setLeft((int)((5d / 100 * width)));
views.get("lblbuildingarea").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel5").vw.setTop((int)((views.get("lblbuildingarea").vw.getTop())+(views.get("lblbuildingarea").vw.getHeight())));
views.get("panel5").vw.setHeight((int)((views.get("panel2").vw.getHeight())));
views.get("panel5").vw.setLeft((int)((5d / 100 * width)));
views.get("panel5").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("buildingarea").vw.setLeft((int)((0d / 100 * width)));
views.get("buildingarea").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("buildingarea").vw.setTop((int)((views.get("standingyear").vw.getTop())));
views.get("buildingarea").vw.setHeight((int)((views.get("standingyear").vw.getHeight())));
views.get("lbllandarea").vw.setHeight((int)((views.get("lblbuildingarea").vw.getHeight())));
views.get("lbllandarea").vw.setTop((int)((views.get("panel5").vw.getTop())+(views.get("panel5").vw.getHeight())+(2d / 100 * height)));
views.get("lbllandarea").vw.setLeft((int)((5d / 100 * width)));
views.get("lbllandarea").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel3").vw.setHeight((int)((views.get("panel5").vw.getHeight())));
views.get("panel3").vw.setTop((int)((views.get("lbllandarea").vw.getTop())+(views.get("lbllandarea").vw.getHeight())));
views.get("panel3").vw.setLeft((int)((5d / 100 * width)));
views.get("panel3").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("landarea").vw.setHeight((int)((views.get("buildingarea").vw.getHeight())));
views.get("landarea").vw.setTop((int)((views.get("buildingarea").vw.getTop())));
views.get("landarea").vw.setLeft((int)((0d / 100 * width)));
views.get("landarea").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblparkingarea").vw.setHeight((int)((views.get("lblbuildingarea").vw.getHeight())));
views.get("lblparkingarea").vw.setTop((int)((views.get("panel3").vw.getTop())+(views.get("panel3").vw.getHeight())+(2d / 100 * height)));
views.get("lblparkingarea").vw.setLeft((int)((5d / 100 * width)));
views.get("lblparkingarea").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel6").vw.setHeight((int)((views.get("panel3").vw.getHeight())));
views.get("panel6").vw.setTop((int)((views.get("lblparkingarea").vw.getTop())+(views.get("lblparkingarea").vw.getHeight())));
views.get("panel6").vw.setLeft((int)((5d / 100 * width)));
views.get("panel6").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("parkingarea").vw.setHeight((int)((views.get("panel6").vw.getHeight())));
views.get("parkingarea").vw.setTop((int)((views.get("landarea").vw.getTop())));
views.get("parkingarea").vw.setLeft((int)((0d / 100 * width)));
views.get("parkingarea").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblelectric").vw.setTop((int)((views.get("panel6").vw.getTop())+(views.get("panel6").vw.getHeight())+(2d / 100 * height)));
views.get("lblelectric").vw.setHeight((int)((views.get("lblparkingarea").vw.getHeight())));
views.get("lblelectric").vw.setLeft((int)((5d / 100 * width)));
views.get("lblelectric").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panelelectricity").vw.setTop((int)((views.get("lblelectric").vw.getTop())+(views.get("lblelectric").vw.getHeight())));
views.get("panelelectricity").vw.setLeft((int)((5d / 100 * width)));
views.get("panelelectricity").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panelelectricity").vw.setHeight((int)((views.get("panel6").vw.getHeight())));
views.get("electricity").vw.setTop((int)((views.get("parkingarea").vw.getTop())));
views.get("electricity").vw.setHeight((int)((views.get("panelelectricity").vw.getHeight())));
views.get("electricity").vw.setLeft((int)((0d / 100 * width)));
views.get("electricity").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblcons").vw.setTop((int)((views.get("panelelectricity").vw.getTop())+(views.get("panelelectricity").vw.getHeight())+(2d / 100 * height)));
views.get("lblcons").vw.setHeight((int)((views.get("lblelectric").vw.getHeight())));
views.get("lblcons").vw.setLeft((int)((5d / 100 * width)));
views.get("lblcons").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel7").vw.setTop((int)((views.get("lblcons").vw.getTop())+(views.get("lblcons").vw.getHeight())));
views.get("panel7").vw.setLeft((int)((5d / 100 * width)));
views.get("panel7").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel7").vw.setHeight((int)((views.get("panelelectricity").vw.getHeight())));
views.get("construction").vw.setHeight((int)((views.get("panel7").vw.getHeight())));
views.get("construction").vw.setTop((int)((views.get("electricity").vw.getTop())));
views.get("construction").vw.setLeft((int)((0d / 100 * width)));
views.get("construction").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("btnsavechanges").vw.setTop((int)((views.get("panel7").vw.getTop())+(views.get("panel7").vw.getHeight())+(5d / 100 * height)));
views.get("btnsavechanges").vw.setHeight((int)((8d / 100 * height)));
views.get("btnsavechanges").vw.setLeft((int)((5d / 100 * width)));
views.get("btnsavechanges").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));

}
}