package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_officeedit3{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("panelbuildinglist").vw.setWidth((int)((100d / 100 * width)));
views.get("panelbuildinglist").vw.setHeight((int)((130d / 100 * height)));
views.get("officename").vw.setHeight((int)((10d / 100 * width)));
views.get("paneltypeoffice").vw.setWidth((int)((100d / 100 * width)));
views.get("panel2").vw.setWidth((int)((100d / 100 * width)));
views.get("panel3").vw.setWidth((int)((100d / 100 * width)));
views.get("panelelectricity").vw.setWidth((int)((100d / 100 * width)));
views.get("pfacility").vw.setWidth((int)((100d / 100 * width)));
views.get("clv1").vw.setWidth((int)((100d / 100 * width)));
views.get("paneltypeoffice").vw.setHeight((int)((16d / 100 * width)));
views.get("panel2").vw.setHeight((int)((16d / 100 * width)));
views.get("panel3").vw.setHeight((int)((16d / 100 * width)));
views.get("panelelectricity").vw.setHeight((int)((16d / 100 * width)));
views.get("pfacility").vw.setHeight((int)((118d * scale)));
views.get("lbltypeofoffice").vw.setHeight((int)((8d / 100 * width)));
views.get("typeofoffice").vw.setHeight((int)((10d / 100 * width)));
views.get("lblstandingyear").vw.setHeight((int)((8d / 100 * width)));
views.get("standingyear").vw.setHeight((int)((10d / 100 * width)));
views.get("lblbuildingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("buildingarea").vw.setHeight((int)((10d / 100 * width)));
views.get("lbllandarea").vw.setHeight((int)((8d / 100 * width)));
views.get("landarea").vw.setHeight((int)((10d / 100 * width)));
views.get("lblparkingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("parkingarea").vw.setHeight((int)((10d / 100 * width)));
views.get("lblelectric").vw.setHeight((int)((8d / 100 * width)));
views.get("electricity").vw.setHeight((int)((10d / 100 * width)));
views.get("lblcons").vw.setHeight((int)((8d / 100 * width)));
views.get("construction").vw.setHeight((int)((10d / 100 * width)));
views.get("lblfacility").vw.setHeight((int)((26d * scale)));
views.get("officename").vw.setTop((int)((5d / 100 * height)));
views.get("lbltypeofoffice").vw.setTop((int)((0d / 100 * width)));
views.get("typeofoffice").vw.setTop((int)((8d / 100 * width)));
views.get("lblstandingyear").vw.setTop((int)((0d / 100 * width)));
views.get("standingyear").vw.setTop((int)((8d / 100 * width)));
views.get("lblbuildingarea").vw.setTop((int)((0d / 100 * width)));
views.get("buildingarea").vw.setTop((int)((8d / 100 * width)));
views.get("lbllandarea").vw.setTop((int)((0d / 100 * width)));
views.get("landarea").vw.setTop((int)((8d / 100 * width)));
views.get("lblparkingarea").vw.setTop((int)((0d / 100 * width)));
views.get("parkingarea").vw.setTop((int)((8d / 100 * width)));
views.get("lblelectric").vw.setTop((int)((0d / 100 * width)));
views.get("electricity").vw.setTop((int)((8d / 100 * width)));
views.get("lblcons").vw.setTop((int)((0d / 100 * width)));
views.get("construction").vw.setTop((int)((8d / 100 * width)));
views.get("lblfacility").vw.setTop((int)((0d / 100 * width)));
views.get("clv1").vw.setTop((int)((8d / 100 * width)));
views.get("paneltypeoffice").vw.setTop((int)((15d / 100 * height)));
views.get("panel2").vw.setTop((int)((31d / 100 * height)));
views.get("panel3").vw.setTop((int)((47d / 100 * height)));
views.get("panelelectricity").vw.setTop((int)((63d / 100 * height)));
views.get("pfacility").vw.setTop((int)((79d / 100 * height)));
views.get("officename").vw.setLeft((int)((5d / 100 * width)));
views.get("officename").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("lbltypeofoffice").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltypeofoffice").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("typeofoffice").vw.setLeft((int)((0d / 100 * width)));
views.get("typeofoffice").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("lblstandingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("lblstandingyear").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("standingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("standingyear").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("lblbuildingarea").vw.setLeft((int)((46d / 100 * width)));
views.get("lblbuildingarea").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("buildingarea").vw.setLeft((int)((46d / 100 * width)));
views.get("buildingarea").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("lbllandarea").vw.setLeft((int)((0d / 100 * width)));
views.get("lbllandarea").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("landarea").vw.setLeft((int)((0d / 100 * width)));
views.get("landarea").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("lblparkingarea").vw.setLeft((int)((46d / 100 * width)));
views.get("lblparkingarea").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("parkingarea").vw.setLeft((int)((46d / 100 * width)));
views.get("parkingarea").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("lblelectric").vw.setLeft((int)((0d / 100 * width)));
views.get("lblelectric").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("electricity").vw.setLeft((int)((0d / 100 * width)));
views.get("electricity").vw.setWidth((int)((45d / 100 * width) - ((0d / 100 * width))));
views.get("lblcons").vw.setLeft((int)((46d / 100 * width)));
views.get("lblcons").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("construction").vw.setLeft((int)((46d / 100 * width)));
views.get("construction").vw.setWidth((int)((90d / 100 * width) - ((46d / 100 * width))));
views.get("lblfacility").vw.setLeft((int)((0d / 100 * width)));
views.get("lblfacility").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("clv1").vw.setLeft((int)((0d / 100 * width)));
views.get("clv1").vw.setWidth((int)((90d / 100 * width) - ((0d / 100 * width))));
views.get("paneltypeoffice").vw.setLeft((int)((5d / 100 * width)));
views.get("paneltypeoffice").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel2").vw.setLeft((int)((5d / 100 * width)));
views.get("panel2").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panel3").vw.setLeft((int)((5d / 100 * width)));
views.get("panel3").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("panelelectricity").vw.setLeft((int)((5d / 100 * width)));
views.get("panelelectricity").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));
views.get("pfacility").vw.setLeft((int)((5d / 100 * width)));
views.get("pfacility").vw.setWidth((int)((95d / 100 * width) - ((5d / 100 * width))));

}
}