package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_office_tabdetail{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("lbltypeofoffice").vw.setHeight((int)((6d / 100 * height)));
views.get("typeofoffice").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblstandingyear").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("standingyear").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblbuildingarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("buildingarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lbllandarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("landarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblparkingarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("parkingarea").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblelectric").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("electricity").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblcons").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("construction").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblfacility").vw.setHeight((int)((views.get("lbltypeofoffice").vw.getHeight())));
views.get("label2").vw.setHeight((int)((8d / 100 * height)));
views.get("lbltypeofoffice").vw.setTop((int)((0d / 100 * height)));
views.get("typeofoffice").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())+(views.get("lbltypeofoffice").vw.getHeight())));
views.get("lblstandingyear").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("standingyear").vw.setTop((int)((views.get("lblstandingyear").vw.getTop())+(views.get("lblstandingyear").vw.getHeight())));
views.get("lblbuildingarea").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("buildingarea").vw.setTop((int)((views.get("lblbuildingarea").vw.getTop())+(views.get("lblbuildingarea").vw.getHeight())));
views.get("lbllandarea").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("landarea").vw.setTop((int)((views.get("lbllandarea").vw.getTop())+(views.get("lbllandarea").vw.getHeight())));
views.get("lblparkingarea").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("parkingarea").vw.setTop((int)((views.get("lblparkingarea").vw.getTop())+(views.get("lblparkingarea").vw.getHeight())));
views.get("lblelectric").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("electricity").vw.setTop((int)((views.get("lblelectric").vw.getTop())+(views.get("lblelectric").vw.getHeight())));
views.get("lblcons").vw.setTop((int)((views.get("lbltypeofoffice").vw.getTop())));
views.get("construction").vw.setTop((int)((views.get("lblcons").vw.getTop())+(views.get("lblcons").vw.getHeight())));
views.get("lblfacility").vw.setTop((int)((2d / 100 * height)));
views.get("clv1").vw.setTop((int)((views.get("lblfacility").vw.getTop())+(views.get("lblfacility").vw.getHeight())));
views.get("panel4").vw.setLeft((int)((4d / 100 * width)));
views.get("panel4").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("paneltypeoffice").vw.setHeight((int)((views.get("typeofoffice").vw.getTop())+(views.get("typeofoffice").vw.getHeight())));
views.get("panel2").vw.setHeight((int)((views.get("standingyear").vw.getTop())+(views.get("standingyear").vw.getHeight())));
views.get("panel3").vw.setHeight((int)((views.get("landarea").vw.getTop())+(views.get("landarea").vw.getHeight())));
views.get("panelelectricity").vw.setHeight((int)((views.get("electricity").vw.getTop())+(views.get("electricity").vw.getHeight())));
views.get("pfacility").vw.setHeight((int)((118d * scale)));
views.get("lbltypeofoffice").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltypeofoffice").vw.setWidth((int)((84d / 100 * width) - ((0d / 100 * width))));
views.get("typeofoffice").vw.setLeft((int)((0d / 100 * width)));
views.get("typeofoffice").vw.setWidth((int)((84d / 100 * width) - ((0d / 100 * width))));
views.get("lblstandingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("lblstandingyear").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("standingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("standingyear").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblbuildingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("lblbuildingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("buildingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("buildingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lbllandarea").vw.setLeft((int)((0d / 100 * width)));
views.get("lbllandarea").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("landarea").vw.setLeft((int)((0d / 100 * width)));
views.get("landarea").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblparkingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("lblparkingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("parkingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("parkingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lblelectric").vw.setLeft((int)((0d / 100 * width)));
views.get("lblelectric").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("electricity").vw.setLeft((int)((0d / 100 * width)));
views.get("electricity").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblcons").vw.setLeft((int)((42d / 100 * width)));
views.get("lblcons").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("construction").vw.setLeft((int)((42d / 100 * width)));
views.get("construction").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lblfacility").vw.setLeft((int)((4d / 100 * width)));
views.get("lblfacility").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("clv1").vw.setLeft((int)((4d / 100 * width)));
views.get("clv1").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("paneltypeoffice").vw.setLeft((int)((4d / 100 * width)));
views.get("paneltypeoffice").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("label2").vw.setLeft((int)((4d / 100 * width)));
views.get("label2").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panel2").vw.setLeft((int)((4d / 100 * width)));
views.get("panel2").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panel3").vw.setLeft((int)((4d / 100 * width)));
views.get("panel3").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panelelectricity").vw.setLeft((int)((4d / 100 * width)));
views.get("panelelectricity").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("pfacility").vw.setLeft((int)((4d / 100 * width)));
views.get("pfacility").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("panel4").vw.setTop((int)((2d / 100 * height)));
views.get("label2").vw.setTop((int)((2d / 100 * height)));
views.get("paneltypeoffice").vw.setTop((int)((views.get("label2").vw.getTop())+(views.get("label2").vw.getHeight())+(2d / 100 * height)));
views.get("panel2").vw.setTop((int)((views.get("paneltypeoffice").vw.getTop())+(views.get("paneltypeoffice").vw.getHeight())+(2d / 100 * height)));
views.get("panel3").vw.setTop((int)((views.get("panel2").vw.getTop())+(views.get("panel2").vw.getHeight())+(2d / 100 * height)));
views.get("panelelectricity").vw.setTop((int)((views.get("panel3").vw.getTop())+(views.get("panel3").vw.getHeight())+(2d / 100 * height)));
views.get("panel4").vw.setHeight((int)((views.get("panelelectricity").vw.getTop())+(views.get("panelelectricity").vw.getHeight())+(2d / 100 * height)));
views.get("pfacility").vw.setTop((int)((views.get("panel4").vw.getTop())+(views.get("panel4").vw.getHeight())+(2d / 100 * height)));
views.get("editbtn").vw.setLeft((int)((80d / 100 * width)));
views.get("editbtn").vw.setWidth((int)((94d / 100 * width) - ((80d / 100 * width))));
views.get("editbtn").vw.setHeight((int)((10d / 100 * height)));
views.get("editbtn").vw.setTop((int)((views.get("panel4").vw.getTop())+(views.get("label2").vw.getTop())));
views.get("editfacility").vw.setTop((int)((0d / 100 * height)));
views.get("editfacility").vw.setHeight((int)((views.get("editbtn").vw.getHeight())));
views.get("editfacility").vw.setLeft((int)((78d / 100 * width)));
views.get("editfacility").vw.setWidth((int)((92d / 100 * width) - ((78d / 100 * width))));

}
}