package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_worshipdetail2{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("panelbuildinglist").vw.setWidth((int)((100d / 100 * width)));
views.get("panelbuildinglist").vw.setHeight((int)((130d / 100 * height)));
views.get("panel1").vw.setHeight((int)((12d / 100 * height)));
views.get("panel1").vw.setLeft((int)((0d / 100 * width)));
views.get("panel1").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("panel4").vw.setLeft((int)((4d / 100 * width)));
views.get("panel4").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("panel5").vw.setLeft((int)((4d / 100 * width)));
views.get("panel5").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("panel5").vw.setHeight((int)((8d / 100 * height)));
views.get("pnlname").vw.setHeight((int)((21d / 100 * height)));
views.get("pnlname").vw.setLeft((int)((4d / 100 * width)));
views.get("pnlname").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("worshipname").vw.setLeft((int)((4d / 100 * width)));
views.get("worshipname").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("label1").vw.setLeft((int)((4d / 100 * width)));
views.get("label1").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("paneltypeworship").vw.setHeight((int)((17d / 100 * width)));
views.get("panel2").vw.setHeight((int)((17d / 100 * width)));
views.get("panel3").vw.setHeight((int)((17d / 100 * width)));
views.get("panelelectricity").vw.setHeight((int)((17d / 100 * width)));
views.get("pfacility").vw.setHeight((int)((118d * scale)));
views.get("lbltypeofworship").vw.setHeight((int)((8d / 100 * width)));
views.get("typeofworship").vw.setHeight((int)((8d / 100 * width)));
views.get("lblstandingyear").vw.setHeight((int)((8d / 100 * width)));
views.get("standingyear").vw.setHeight((int)((8d / 100 * width)));
views.get("lblbuildingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("buildingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("lbllandarea").vw.setHeight((int)((8d / 100 * width)));
views.get("landarea").vw.setHeight((int)((8d / 100 * width)));
views.get("lblparkingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("parkingarea").vw.setHeight((int)((8d / 100 * width)));
views.get("lblelectric").vw.setHeight((int)((8d / 100 * width)));
views.get("electricity").vw.setHeight((int)((8d / 100 * width)));
views.get("lblcons").vw.setHeight((int)((8d / 100 * width)));
views.get("construction").vw.setHeight((int)((8d / 100 * width)));
views.get("lblfacility").vw.setHeight((int)((26d * scale)));
views.get("label2").vw.setHeight((int)((8d / 100 * height)));
views.get("buttonmap").vw.setHeight((int)((views.get("panel5").vw.getHeight())));
views.get("buttongallery").vw.setHeight((int)((views.get("buttonmap").vw.getHeight())));
views.get("buttondetail").vw.setHeight((int)((views.get("buttongallery").vw.getHeight())));
views.get("buttonmap").vw.setLeft((int)((0d / 100 * width)));
views.get("buttonmap").vw.setWidth((int)((32d / 100 * width) - ((0d / 100 * width))));
views.get("buttondetail").vw.setLeft((int)((31d / 100 * width)));
views.get("buttondetail").vw.setWidth((int)((64d / 100 * width) - ((31d / 100 * width))));
views.get("buttongallery").vw.setLeft((int)((63d / 100 * width)));
views.get("buttongallery").vw.setWidth((int)((92d / 100 * width) - ((63d / 100 * width))));
views.get("buttonmap").vw.setTop((int)((0d / 100 * height)));
views.get("buttongallery").vw.setTop((int)((views.get("buttonmap").vw.getTop())));
views.get("buttondetail").vw.setTop((int)((views.get("buttongallery").vw.getTop())));
views.get("label1").vw.setTop((int)((1d / 100 * height)));
views.get("worshipname").vw.setTop((int)((views.get("label1").vw.getTop())+(views.get("label1").vw.getHeight())));
views.get("lbltypeofworship").vw.setTop((int)((0d / 100 * width)));
views.get("typeofworship").vw.setTop((int)((8d / 100 * width)));
views.get("lblstandingyear").vw.setTop((int)((0d / 100 * width)));
views.get("standingyear").vw.setTop((int)((8d / 100 * width)));
views.get("lblbuildingarea").vw.setTop((int)((0d / 100 * width)));
views.get("buildingarea").vw.setTop((int)((8d / 100 * width)));
views.get("lbllandarea").vw.setTop((int)((0d / 100 * width)));
views.get("landarea").vw.setTop((int)((8d / 100 * width)));
views.get("lblparkingarea").vw.setTop((int)((0d / 100 * width)));
views.get("parkingarea").vw.setTop((int)((8d / 100 * width)));
views.get("lblelectric").vw.setTop((int)((0d / 100 * width)));
views.get("electricity").vw.setTop((int)((8d / 100 * width)));
views.get("lblcons").vw.setTop((int)((0d / 100 * width)));
views.get("construction").vw.setTop((int)((8d / 100 * width)));
views.get("lblfacility").vw.setTop((int)((0d / 100 * width)));
views.get("clv1").vw.setTop((int)((8d / 100 * width)));
views.get("lbltypeofworship").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltypeofworship").vw.setWidth((int)((84d / 100 * width) - ((0d / 100 * width))));
views.get("typeofworship").vw.setLeft((int)((0d / 100 * width)));
views.get("typeofworship").vw.setWidth((int)((84d / 100 * width) - ((0d / 100 * width))));
views.get("lblstandingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("lblstandingyear").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("standingyear").vw.setLeft((int)((0d / 100 * width)));
views.get("standingyear").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblbuildingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("lblbuildingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("buildingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("buildingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lbllandarea").vw.setLeft((int)((0d / 100 * width)));
views.get("lbllandarea").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("landarea").vw.setLeft((int)((0d / 100 * width)));
views.get("landarea").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblparkingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("lblparkingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("parkingarea").vw.setLeft((int)((42d / 100 * width)));
views.get("parkingarea").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lblelectric").vw.setLeft((int)((0d / 100 * width)));
views.get("lblelectric").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("electricity").vw.setLeft((int)((0d / 100 * width)));
views.get("electricity").vw.setWidth((int)((42d / 100 * width) - ((0d / 100 * width))));
views.get("lblcons").vw.setLeft((int)((42d / 100 * width)));
views.get("lblcons").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("construction").vw.setLeft((int)((42d / 100 * width)));
views.get("construction").vw.setWidth((int)((84d / 100 * width) - ((42d / 100 * width))));
views.get("lblfacility").vw.setLeft((int)((4d / 100 * width)));
views.get("lblfacility").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("clv1").vw.setLeft((int)((4d / 100 * width)));
views.get("clv1").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("paneltypeworship").vw.setLeft((int)((4d / 100 * width)));
views.get("paneltypeworship").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("label2").vw.setLeft((int)((4d / 100 * width)));
views.get("label2").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panel2").vw.setLeft((int)((4d / 100 * width)));
views.get("panel2").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panel3").vw.setLeft((int)((4d / 100 * width)));
views.get("panel3").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("panelelectricity").vw.setLeft((int)((4d / 100 * width)));
views.get("panelelectricity").vw.setWidth((int)((88d / 100 * width) - ((4d / 100 * width))));
views.get("pfacility").vw.setLeft((int)((4d / 100 * width)));
views.get("pfacility").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("panelbutton").vw.setLeft((int)((4d / 100 * width)));
views.get("panelbutton").vw.setWidth((int)((96d / 100 * width) - ((4d / 100 * width))));
views.get("btnmap").vw.setLeft((int)((0d / 100 * width)));
views.get("btnmap").vw.setWidth((int)((42.5d / 100 * width) - ((0d / 100 * width))));
views.get("btngallery").vw.setLeft((int)((47.5d / 100 * width)));
views.get("btngallery").vw.setWidth((int)((90d / 100 * width) - ((47.5d / 100 * width))));
views.get("btnmap").vw.setTop((int)((0d / 100 * height)));
views.get("btngallery").vw.setTop((int)((0d / 100 * height)));
views.get("btnmap").vw.setHeight((int)((50d * scale)));
views.get("btngallery").vw.setHeight((int)((50d * scale)));
views.get("panelbutton").vw.setHeight((int)((50d * scale)));
views.get("ivgallery").vw.setTop((int)((10d * scale)));
views.get("ivgallery").vw.setHeight((int)((40d * scale) - ((10d * scale))));
views.get("ivmap").vw.setTop((int)((10d * scale)));
views.get("ivmap").vw.setHeight((int)((40d * scale) - ((10d * scale))));
views.get("lblgallery").vw.setTop((int)((10d * scale)));
views.get("lblgallery").vw.setHeight((int)((40d * scale) - ((10d * scale))));
views.get("lblmap").vw.setTop((int)((10d * scale)));
views.get("lblmap").vw.setHeight((int)((40d * scale) - ((10d * scale))));
views.get("ivgallery").vw.setLeft((int)((20d * scale)));
views.get("ivgallery").vw.setWidth((int)((60d * scale) - ((20d * scale))));
views.get("ivmap").vw.setLeft((int)((20d * scale)));
views.get("ivmap").vw.setWidth((int)((42d * scale) - ((20d * scale))));
views.get("lblgallery").vw.setLeft((int)((18d / 100 * width)));
views.get("lblgallery").vw.setWidth((int)((42.5d / 100 * width) - ((18d / 100 * width))));
views.get("lblmap").vw.setLeft((int)((15d / 100 * width)));
views.get("lblmap").vw.setWidth((int)((42.5d / 100 * width) - ((15d / 100 * width))));
views.get("panel1").vw.setTop((int)((0d / 100 * height)));
views.get("pnlname").vw.setTop((int)((2d / 100 * height)));
views.get("panel5").vw.setTop((int)((views.get("pnlname").vw.getTop())+(views.get("pnlname").vw.getHeight())+(2d / 100 * height)));
views.get("panel4").vw.setTop((int)((views.get("panel5").vw.getTop())+(views.get("panel5").vw.getHeight())+(2d / 100 * height)));
views.get("label2").vw.setTop((int)((1d / 100 * height)));
views.get("paneltypeworship").vw.setTop((int)((views.get("label2").vw.getTop())+(views.get("label2").vw.getHeight())+(2d / 100 * height)));
views.get("panel2").vw.setTop((int)((views.get("paneltypeworship").vw.getTop())+(views.get("paneltypeworship").vw.getHeight())+(2d / 100 * height)));
views.get("panel3").vw.setTop((int)((views.get("panel2").vw.getTop())+(views.get("panel2").vw.getHeight())+(2d / 100 * height)));
views.get("panelelectricity").vw.setTop((int)((views.get("panel3").vw.getTop())+(views.get("panel3").vw.getHeight())+(2d / 100 * height)));
views.get("panel4").vw.setHeight((int)((views.get("panelelectricity").vw.getTop())+(views.get("panelelectricity").vw.getHeight())+(2d / 100 * height)));
views.get("pfacility").vw.setTop((int)((views.get("panel4").vw.getTop())+(views.get("panel4").vw.getHeight())+(2d / 100 * height)));
views.get("panelbuildinglist").vw.setHeight((int)((views.get("panel4").vw.getTop())+(views.get("panel4").vw.getHeight())+(2d / 100 * height)));

}
}